import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/**/*.ts", "!src/**/*.test.ts"],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  external: [
    "@candor/identifiers",
    "@candor/core-types",
    "@candor/ipld-database",
    "@libp2p/mplex",
    "ajv",
    "did-jwt",
    "did-resolver",
    "dids",
    "emittery",
    "ipfs-core",
    "it-length-prefixed",
    "it-map",
    "it-pipe",
    "key-did-provider-ed25519",
    "key-did-resolver",
    "localforage",
    "microbundle",
    "multiformats",
    "uint8arrays",
    "uuid",
    "@candor/plugin-offline-sync-core",
    "@candor/protocol",
    "@chainsafe/libp2p-gossipsub",
    "@chainsafe/libp2p-noise",
    "@libp2p/crypto",
    "@libp2p/interface-connection",
    "@libp2p/interface-peer-id",
    "@libp2p/peer-id",
    "@libp2p/peer-id-factory",
    "@libp2p/websockets",
    "@multiformats/multiaddr",
    "@stablelib/ed25519",
    "@types/ajv",
    "@types/lodash-es",
    "@types/node",
    "@types/uuid",
    "dotenv",
    "ipfs-core-types",
    "it-pushable",
    "libp2p",
    "lodash-es",
    "@chainsafe/libp2p-gossipsub",
    "@chainsafe/libp2p-noise",
    "@libp2p/crypto",
    "@libp2p/peer-id",
    "@libp2p/peer-id-factory",
    "@libp2p/websockets",
    "@multiformats/multiaddr",
    "@stablelib/ed25519",
    "libp2p",
  ],
});
