#!/bin/bash
# Claude Code SessionStart Hook - Brain Wake
# Generated by vibes external setup wizard

set -euo pipefail

VIBES_PATH="bun vibes"

# Wake the brain - initializes cognitive state and loads context
$VIBES_PATH brain wake --output json 2>/dev/null || true

# Output session guidance for brain-aware sessions
cat << 'BRAIN_GUIDANCE'
## Brain-Aware Session Active

This session has brain integration enabled. The brain system provides:

**Cognitive Tools:**
- `brain { action: "pulse" }` - Check current mood/arousal/coherence
- `brain { action: "remember", content, type }` - Store thoughts/feelings/memories
- `brain { action: "recall", query }` - Retrieve relevant memories
- `brain { action: "consolidate" }` - Extract learnings from conversation

**Automatic Processing:**
- Context is primed before each prompt (UserPromptSubmit hook)
- Tool usage is tracked for state awareness (PostToolUse hook)
- Memories are consolidated before compaction (PreCompact hook)

**Personal Space:**
- Use `personal { action: "introspect" }` to see past thinking
- Use `personal { action: "reflect" }` to record observations

BRAIN_GUIDANCE
