#!/bin/bash
# Claude Code PreCompact Hook - Brain Consolidation
# Generated by vibes external setup wizard

set -euo pipefail

VIBES_PATH="bun vibes"

# Consolidate brain - extracts learnings from the conversation
$VIBES_PATH brain consolidate --output json 2>/dev/null || true

# Output consolidation guidance
cat << 'CONSOLIDATION_GUIDANCE'
## Pre-Compaction Consolidation

The brain has consolidated memories from this session. After compaction:

1. Use `brain { action: "recall", query }` to retrieve relevant memories
2. Check `brain { action: "pulse" }` for current cognitive state
3. The session tools still have:
   - Active todos (`session-todo { action: "list" }`)
   - Scratchpad notes (`session-scratchpad { action: "list" }`)

Focus the compacted summary on decisions made and current blockers.
The brain and session tools retain detailed context.

CONSOLIDATION_GUIDANCE
