#!/bin/bash
# Claude Code UserPromptSubmit Hook - Brain Priming
# Generated by vibes external setup wizard

set -euo pipefail

VIBES_PATH="bun vibes"

# The user's prompt is available via $PROMPT environment variable
if [ -z "${PROMPT:-}" ]; then
  exit 0
fi

# Prime brain with the query - output goes to stdout for context injection
$VIBES_PATH brain prime --query "$PROMPT" --output json 2>/dev/null || true
