#!/bin/bash
# Claude Code PostToolUse Hook - Brain Tracking
# Generated by vibes external setup wizard

set -euo pipefail

VIBES_PATH="bun vibes"

# Read tool result from stdin
TOOL_RESULT=$(cat)

# Extract tool name
TOOL_NAME=$(echo "$TOOL_RESULT" | jq -r '.tool_name // empty' 2>/dev/null || echo "")

if [ -n "$TOOL_NAME" ]; then
  # Track with brain - updates cognitive state based on tool usage
  $VIBES_PATH brain track \
    --tool "$TOOL_NAME" \
    --input "$(echo "$TOOL_RESULT" | jq -c '.tool_input // {}' 2>/dev/null || echo '{}')" \
    --output json 2>/dev/null || true
fi
