import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/**/*.ts", "!src/**/*.test.ts"],
  format: ["esm", "cjs"],
  dts: true,
  sourcemap: true,
  external: [
    "@candor/identifiers",
    "@candor/core-types",
    "@candor/ipld-database",
    "@candor/plugin-offline-sync-core",
    "@candor/plugin-social-core",
    "@candor/protocol",
    "@candor/tsconfig",
    "@multiformats/multiaddr",
    "@types/uuid",
    "did-jwt",
    "dids",
    "emittery",
    "multiformats",
    "tsup",
    "typescript",
    "vitest",
    "@multiformats/multiaddr",
    "did-jwt",
    "dids",
    "emittery",
    "multiformats",
    "uuid",
  ],
});
