[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.17"
mnemonic_paths = './mnemonic'

[profile.testnet]
eth_rpc_url = 'https://testnet.candor.social'
chain_id=4242

# See more config options https://github.com/foundry-rs/foundry/tree/master/config